MySQL: false
MySQLhost: host
MySQLuser: user
MySQLpass: pw
MySQLdb: db
MySQLport: 3306
MySQLtable: pvpstats
MySQLkilltable: pvpkillstats

PVPArena: false
checkabuse: true
updatecheck: true
autodownload: true