name: pvpstats
main: praxis.slipcor.pvpstats.PVPStats
version: 0.4.1
author: slipcor
soft-depends: pvparena
website: http://dev.bukkit.org/server-mods/pvp-stats/
commands:
    pvpstats:
        description: display or reload
        aliases: stats
        usage: |
            /pvpstats - show your pvp stats
            /pvpstats [player] - show player's pvp stats
            /pvpstats [amount] - show the top [amount] players (K-D)
            /pvpstats top [amount] - show the top [amount] players (K-D)
            /pvpstats top [type] - show the top 10 players of the type
            /pvpstats top [type] [amount] - show the top [amount] players of the type
            /pvpstats reload - reload the configs
permissions:
    pvpstats.reload:
        description: Ability to reload
        default: op
    pvpstats.wipe:
        description: Ability to wipe
        default: op
    pvpstats.count:
        description: Permission to be counted
        default: true